GET http://130.211.107.182:10000/pmsint/practice/195900
Accept: application/json

###
GET http://130.211.107.182:10000/pmsint/practice
Accept: application/json

###
GET http://130.211.107.182:10000/pmsint/practice/195900/departments
Accept: application/json

###
GET http://130.211.107.182:10000/pmsint/practice/195900/providers
Accept: application/json

###
