GET http://35.205.222.180:10000/pmsint/practice/195900
Accept: application/json

###
GET http://35.205.222.180:10000/pmsint/practice
Accept: application/json

###
GET http://35.205.222.180:10000/pmsint/practice/195900/departments
Accept: application/json

###
GET http://35.205.222.180:10000/pmsint/practice/195900/providers
Accept: application/json

###
