imports:
  - path: manifests/backend_manifest.yaml
  - path: templates/cnt_vm_1.jinja
    name: backend-vm-1.jinja
  - path: templates/bq-logs-dataset.jinja
    name: bq-logs-dataset.jinja
  - path: templates/service-account.jinja
    name: service-account.jinja
  - path: templates/custom_role.jinja
    name: custom_role.jinja
  - path: templates/pmsint_bucket.jinja
    name: pmsint_bucket.jinja

resources:
  - name: sa-storage-operator
    type: service-account.jinja
    properties:
      name: storage-operator

  - name: storage-operator-role
    type: custom_role.jinja
    properties:
      roleId: StorageOperator
      title: Storage Operator
      description: Storage Operator
      stage: GA
      includedPermissions:
        - storage.objects.create
        - storage.objects.get
        - storage.objects.list
        - storage.objects.update
        - storage.objects.delete

  - name: logs-dataset
    type: bq-logs-dataset.jinja

  - name: allow-http-fw
    type: compute.v1.firewall
    properties:
      allowed:
        - IPProtocol: TCP
          ports: [10000]
      sourceRanges: [ 0.0.0.0/0 ]

  - name: practiceinfo_bucket
    type: pmsint_bucket.jinja
    properties:
      name: practiceinfo
      region: US
      storageClass: STANDARD
      iamrole: projects/da-pms-integration-prototype/roles/StorageOperator
      sa: storage-operator@da-pms-integration-prototype.iam.gserviceaccount.com

  - name: backend
    type: backend-vm-1.jinja
    properties:
      zone: europe-west1-b
      containerManifest: manifests/backend_manifest.yaml
      sa: storage-operator@da-pms-integration-prototype.iam.gserviceaccount.com


